name: TreasureHunts
version: '${version}'
main: org.mahdi.testmode.treasurehunts.TreasureHunts
api-version: '1.20'
commands:
  treasures:
    description: ""
    usage: "/treasures"
  test:
    description: "Test command"
    usage: "/test"
